test: update pipeline template integration config
hydra-genetics/hydra-genetics pull request #255
Opened 2023-05-23 12:38 UTC by elleira

### This PR:

(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)

Added: for new features.
Changed: for changes in existing functionality.
Deprecated: for soon-to-be removed features.
Removed: for now removed features.
Fixed: for any bug fixes.
Security: in case of vulnerabilities.

### Review and tests: 
- [ ] Tests pass
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Code review
- [ ] `CHANGELOG.md` is updated
- [ ] New code is executed and covered by tests, and test approve

2023-05-23 13:12 UTC, jonca79 approved these changes

2023-05-24 09:20 UTC, nnneeennn requested changes

2023-05-24 09:20 UTC, nnneeennn commented on docs/profile.md
> +default-resources: [threads=1, time="04:00:00", partition="core", mem_mb="3074", mem_per_cpu="3074"] # Default resources, overwritten by default values in resourses.yaml
```suggestion
default-resources: [threads=1, time="04:00:00", partition="core", mem_mb="3074", mem_per_cpu="3074"] # Default resources, overwritten by default values in resources.yaml
```

2023-05-24 10:03 UTC, nnneeennn approved these changes

2023-05-24 11:15 UTC, merged